ex2: main_2.o inverte_array.o manipula_array.o
	gcc main_2.o inverte_array.o manipula_array.o -o ex2
main_2.o: main_2.c
	gcc -c main_2.c
inverte_array.o: inverte_array.s
	gcc -c inverte_array.s
manipula_array.o: manipula_array.s
	gcc -c manipula_array.s